version: '3'

services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    volumes:
      - /var/lib/mongodb/data
    ports:
      - '27017:27017'
    logging:
      driver: none